### ISSUE TITLE
I can't build at spawn

### ISSUE THREAD

**Issue by Justsnoopy30** [PeachesMLG/EpicSkyblock#1]
In the EpicSkyblock world, I am trying to build a spawn, but I can't place or break blocks.

**Comment by PeachesMLG** [comment]
Its not designed to have a spawn there. get a plugin such as MultiverseCore: https://www.spigotmc.org/resources/multiverse-core.390/ and make a new world for your spawn?

**Comment by Justsnoopy30** [comment]
I already have Multiverse, but it would be better if I could bypass the spawn protection from EpicSkyblock so users wouldn't need a world loading screen or a separate world.

**Comment by StarBoy228** [comment]
EpicSkyBlock world is only for islands of your players. If you want a custom spawn then contact a builder and get map. Rename it to world and replace ur "world" with that map.

**Comment by Justsnoopy30** [comment]
I just ended up editing with worldedit.
