### ISSUE TITLE
Only 1 Island

### ISSUE THREAD

**Issue by syphenik** [PeachesMLG/EpicSkyblock#13]
On my server my friend created a new island and  now i cant go to my island it teleports me to his island should this be happening?

**Comment by MrKaneki** [comment]
+same problem

**Comment by PeachesMLG** [comment]
This has been fixed and explained in the latest version. Basically im an idiot and accidently changed the config.json so the distance between each island is one block. If you download the latest plugin and let the config regenerate it will fix it or you can manually change the distance to something like 200
