### ISSUE TITLE
Fall Off Island

### ISSUE THREAD

**Issue by Tazler89** [PeachesMLG/EpicSkyblock#16]
Hi i just installed plugin for first time ever, made an island and when jumping off side i got to the bottom and it just spammed teleporting home and i was stuck at the bottom only managed to get back by leaving the world then going back to it

**Comment by PeachesMLG** [comment]
Ill look into this

**Comment by PeachesMLG** [comment]
Fixed 1a992cb9b64ef9000e853ee42521996b7f287d6a
