### ISSUE TITLE
BIG PROBLEM!!!

### ISSUE THREAD

**Issue by Tazler89** [PeachesMLG/EpicSkyblock#17]
So this plugin is effecting all other worlds..... if you are not the owner of a island it stops you braking and placing blocks in all other worlds, i am having to remove this plugin very very bad

**Comment by PeachesMLG** [comment]
Ok, ill fix this soon

**Comment by PeachesMLG** [comment]
Fixed c287ecba06839a9448e902f62b8c22664f4f848b
