### ISSUE TITLE
Error when creating islands

### ISSUE THREAD

**Issue by callum5771** [PeachesMLG/EpicSkyblock#20]
Error when creating islands on Spigot 1.14.4.
Server logs: https://pastebin.com/mCmbpiku

**Comment by PeachesMLG** [comment]
18.09 22:42:11 [Server] INFO Caused by: java.lang.OutOfMemoryError: Metaspace
How much ram does your server have?

**Comment by callum5771** [comment]
4GB, doesn't this mean it overloaded? We can increase the provisioned RAM if necessary.

**Comment by PeachesMLG** [comment]
can you send a timings report?

**Comment by callum5771** [comment]
Increased the servers ram to 6GB from 4GB and it worked flawlessly. Thanks for an awesome plugin!
