### ISSUE TITLE
You cannot invite users to your island

### ISSUE THREAD

**Issue by Justsnoopy30** [PeachesMLG/EpicSkyblock#3]
When trying to invite users to your island, you get "user already has an island," even if the user has no island. It works when manually set in the config and the server restarted, but that's not feasible.

**Comment by Nachfolger1** [comment]
Same situation here.

**Comment by Justsnoopy30** [comment]
src/main/java/com/peaches/epicskyblock/commands/InviteCommand.java

**Comment by PeachesMLG** [comment]
Fixed
