### ISSUE TITLE
When doing /is fly, it always says enabled fly even if fly is already on, and it is not toggled off.

### ISSUE THREAD

**Issue by Justsnoopy30** [PeachesMLG/EpicSkyblock#4]
When doing /is fly, it always says enabled fly even if fly is already on, and it is not toggled off.

**Comment by StarBoy228** [comment]
Hello Justsnoopy32,
I am (HypexMC) and currently helping the developer of this plugin fixing bugs and adding new features. Thanks for reporting this issue. I will get on it and try to fix it as soon as possible.

**Comment by PeachesMLG** [comment]
Fixed: https://github.com/PeachesMLG/EpicSkyblock/commit/0ad4418763b1c3787876e234c63adec1022b65af
